import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/app/components/global/theme-provider'
import Header from '@/app/components/header/Header'
import Footer from '@/app/components/footer/Footer'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html suppressHydrationWarning lang="pl">
            <body className={`antialiased`}>
                <ThemeProvider
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                    attribute="class"
                >
                    <Header />
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    )
}
